const route = require('express').Router();
const adminRoutes = require('./adminRoutes');
const employeeRoutes = require('./employeeRoutes');
const customerRoutes = require('./customerRoutes')
const supplierRoutes = require('./supplierRoutes');
const divisionRoutes = require('./divisionRoutes');
const positionRoutes = require('./positionRoutes');
const brandCategoryRoutes = require('./brandCategoryRoutes');
const brandRoutes = require('./brandRoutes');
const materialRoutes = require('./materialRoutes');
const sizeRoutes = require('./sizeRoutes');
const sizeCategoryRoutes = require('./sizeCategoryRoutes');
const datebookRoutes = require('./datebookRoutes');
const referenceRoutes = require('./referenceRoutes');
const purchaseRoutes = require('./purchaseRoutes');
const materialPurchaseRoutes = require('./materialPurchaseRoutes');
const productRoutes = require('./productRoutes');
const orderRoutes = require('./orderRoutes');
const productOrderRoutes = require('./productOrderRoutes');
const productMaterialRoutes = require('./productMaterialRoutes');
const assignmentRoutes = require('./assignmentRoutes');
const shoppingRoutes = require('./shoppingRoutes');
const paymentRoutes = require('./paymentRoutes');
const internalTransactionRoutes = require('./internalTransactionRoutes');
const generalTransactionRoutes = require('./generalTransactionRoutes');
const accountRoutes = require('./accountRoutes');
const transactionRoutes = require('./transactionRoutes');
const accountTransactionRoutes = require('./accountTransactionRoutes');
const tokenRoutes = require('./tokenRoutes');
const stockRoutes = require('./stockRoutes');
const stockEmployeeRoutes = require('./stockEmployeeRoutes');

route.use('/admins', adminRoutes);
route.use('/employees', employeeRoutes);
route.use('/customers', customerRoutes);
route.use('/suppliers', supplierRoutes);
route.use('/divisions', divisionRoutes);
route.use('/positions', positionRoutes);
route.use('/brands', brandRoutes);
route.use('/brand-categories', brandCategoryRoutes);
route.use('/materials', materialRoutes);
route.use('/material-purchases', materialPurchaseRoutes);
route.use('/sizes', sizeRoutes);
route.use('/size-categories', sizeCategoryRoutes);
route.use('/datebooks', datebookRoutes);
route.use('/references', referenceRoutes);
route.use('/purchases', purchaseRoutes);
route.use('/products', productRoutes);
route.use('/orders', orderRoutes);
route.use('/product-orders', productOrderRoutes);
route.use('/product-materials', productMaterialRoutes);
route.use('/assignments', assignmentRoutes);
route.use('/shoppings', shoppingRoutes);
route.use('/payments', paymentRoutes);
route.use('/internal-transactions', internalTransactionRoutes);
route.use('/general-transactions', generalTransactionRoutes);
route.use('/accounts', accountRoutes);
route.use('/transactions', transactionRoutes);
route.use('/account-transactions', accountTransactionRoutes);
route.use('/tokens', tokenRoutes);
route.use('/stocks', stockRoutes);
route.use('/stock-employees', stockEmployeeRoutes);

module.exports = route;